services:
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    environment:
      - TZ=Europe/Berlin
      - CONFIG_VOLUMES=/config/volumes
    ports:
      - "9090:5800"
      - "3129:3129"
    volumes:
      - ${CONFIG_VOLUMES}/jdownloader:/config
      - ${CONFIG_VOLUMES}/downloads:/downloads
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Berlin
      - CONFIG_VOLUMES=/config/volumes
    ports:
      - 9091:7878
    volumes:
      - ${CONFIG_VOLUMES}/radarr/config:/config
      - ${CONFIG_VOLUMES}/radarr/movies:/movies
      - ${CONFIG_VOLUMES}/downloads:/downloads
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Berlin
      - CONFIG_VOLUMES=/config/volumes
    ports:
      - 9092:8989
    volumes:
      - ${CONFIG_VOLUMES}/sonarr/config:/config
      - ${CONFIG_VOLUMES}/sonarr/tv:/tv
      - ${CONFIG_VOLUMES}/downloads:/downloads
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    restart: unless-stopped
