version: '3.3'
services:
    quasarr:
        container_name: 'Quasarr'
        ports:
            - 'port:8080'
        volumes:
            - '/path/to/config/:/config:rw'
        environment:
            - 'INTERNAL_ADDRESS=http://192.168.1.1:8080'
        image: 'rix1337/docker-quasarr:latest'
