version: '3.3'
services:
    quasarr:
        container_name: 'Quasarr'
        ports:
            - 'port:8080'
        volumes:
            - '/path/to/config/:/config:rw'
        environment:
            - 'INTERNAL_ADDRESS=http://192.168.1.1:8080'
            - 'EXTERNAL_ADDRESS=http://foo.bar/'
            - 'DISCORD=https://discord.com/api/webhooks/1234567890/ABCDEFGHIJKLMN'
        image: 'rix1337/docker-quasarr:latest'
